name: Label Issue

on:
  issues:
    types:
      - opened

jobs:
  issue-label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Label Issue
        uses: ./
        with:
          token: ${{ secrets.TEST_PAT }}
          labels: "state: NEW, progress: BACKLOG"
