name: Label Issue

on:
  issues:
    types:
      - edited

jobs:
  issue-label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Label Issue
        id: label-issue
        uses: ./
        with:
          token: ${{ secrets.TEST_PAT }}
      - name: Label Exists
        if: ${{ steps.label-issue.outputs.LabelExists }}
        run: echo ${{ steps.label-issue.outputs.LabelExists }}
      - name: Label Doesnt Exists
        if: "${{ ! steps.label-issue.outputs.LabelExists }}"
        run: echo "Doesnt Exists" 
